name: Release & Publish to NPM
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run release script
        run: yarn release --ci
      - name: End
        run: echo "All done!"

